### ISSUE TITLE
Touch Actions not Working on ios 13.5.1

### ISSUE THREAD

**Issue by ranchor** [appium/WebDriverAgent#362]
**Warning:**
I am getting below error while using touch action.

```
  "value" : {
    "error" : "unknown command",
    "message" : "Unhandled endpoint: \/session\/B2C3AE2C-7593-4C1B-A55D-053E3860FE63\/wda\/touch\/perform\/%7B'actions':%20%5B%7B'action':%20'press',%20'options':%20%7B'y':%20413.3333333333333,%20'x':%20215.33333333333334%7D%7D,%20%7B'action':%20'release',%20'options':%20%7B%7D%7D%5D%7D -- http:\/\/127.0.0.1:8100\/ with parameters {\n    wildcards =     (\n        \"session\/B2C3AE2C-7593-4C1B-A55D-053E3860FE63\/wda\/touch\/perform\/{'actions': [{'action': 'press', 'options': {'y': 413.3333333333333, 'x': 215.33333333333334}}, {'action': 'release', 'options': {}}]}\"\n    );\n}",
    "traceback" : ""
  },
  "sessionId" : "B2C3AE2C-7593-4C1B-A55D-053E3860FE63"
}.
```

These issues are not tracked. Please create new issues in the main Appium
repository: https://github.com/appium/appium/issues/new

**Comment by KazuCocoa** [comment]
The URL was wrong.
It was `\/session\/B2C3AE2C-7593-4C1B-A55D-053E3860FE63\/wda\/touch\/perform\/{'actions': [{'action': 'press', 'options': {'y': 413.3333333333333, 'x': 215.33333333333334}}, {'action': 'release', 'options': {}}]}`, but `{'actions': [{'action': 'press', 'options': {'y': 413.3333333333333, 'x': 215.33333333333334}}, {'action': 'release', 'options': {}}]}` should be in the body instead of the URL.

btw, if it happened Appium, please report it in https://github.com/appium/appium/issues/new following the template
