### ISSUE TITLE
Dismiss Keyboard not working

### ISSUE THREAD

**Issue by krishtoautomate** [appium/WebDriverAgent#420]
{{DEVICE_URL}}/session/{{SESSSION_ID}}/wda/keyboard/dismiss

**Comment by KazuCocoa** [comment]
Could you share the log?
If the error message had like https://github.com/appium/WebDriverAgent/blob/c7f01c839f9f1284e1319ccce096f6ac96153a40/WebDriverAgentLib/Commands/FBCustomCommands.m#L111 , you can report it to Apple since Appium calls https://developer.apple.com/documentation/uikit/uiinputviewcontroller/1618196-dismisskeyboard?language=objc
