### ISSUE TITLE
Distribution Provisioning profile does not match the entitlement file's value for the get-task-allow entitlement

### ISSUE THREAD

**Issue by Veeru5c4** [appium/WebDriverAgent#445]
I have configured paid developer account provisional profiles changes bundle id
I can able to build "automatically manage signing"  but when I did manual signing I get error like "Distribution Provisioning profile does not match the entitlement file's value for the get-task-allow entitlement" even normal iOS app config same profiles working fine but WebDriverAgentRunner get above error 

Please provide steps how to to config distribution profiles 
<img width="811" alt="Screenshot 2020-12-26 at 1 39 24 PM" src="https://user-images.githubusercontent.com/4330132/103148420-65dae980-4785-11eb-983d-3d2aa8d58789.png">

**Comment by Veeru5c4** [comment]
Xcode : 12.2
Appium : 1.19.1

**Comment by KazuCocoa** [comment]
Probably your provisioning profile does not work for XCTest framework.
I shared with you before in another issue, XCTest bundle is not the same as regular iOS apps. So, _normal iOS app config same profiles working fine but WebDriverAgentRunner get above error_ case could happen.

Afaik, http://appium.io/docs/en/drivers/ios-xcuitest-real-devices/#configuring-the-app-under-test helps.
Your issue is probably https://stackoverflow.com/questions/1003066/what-does-get-task-allow-do-in-xcode

Close this since this is not WDA itself's issue
