### ISSUE TITLE
Assertions: Assertion Failure: Lost connection to testmanagerd

### ISSUE THREAD

**Issue by gffguo** [appium/WebDriverAgent#461]
I don't know why test failed suddenly when WDA was running, and then I started it with Xcode to prompt WDA to exit unexpectedly

Operating environment：
xcode 12.3
carthage 0.34.0
node 14.0.0
wda   commit 359537e52046398fb0ee8489efe259a0fe91bc56 (tag: v2.20.0)

problem：During operation, the log prompts 【Assertions: Assertion Failure: Lost connection to testmanagerd】

WDA information displayed on the console：
[WDA-TEST FAILED.txt](https://github.com/appium/WebDriverAgent/files/5871188/WDA-TEST.FAILED.txt)

enclosure：WebDriverAgentRunner-ADBC5FBC-E937-4AC3-BB24-784E79328ED1/Session-WebDriverAgentRunner-2021-01-24_002011-4sgyz7.log
![image](https://user-images.githubusercontent.com/69896971/105800982-03b71380-5fd3-11eb-999e-f0a192bcf032.png)
![image](https://user-images.githubusercontent.com/69896971/105800989-074a9a80-5fd3-11eb-8338-e120088124c1.png)

**Comment by gffguo** [comment]
Please help me，Thank you very much.

**Comment by KazuCocoa** [comment]
It seems general XCTest(UI) stuff to handle testmanagerd rather than Appium specific issue to me.

https://www.google.com/search?sxsrf=ALeKk02OiE4v249vVvScKfs3aEuMeBFkwQ%3A1611652220243&source=hp&ei=fNwPYIK5DO-t0PEPgJaHmAY&q=xcode+xctest+Lost+connection+to+testmanagerd&oq=xcode+xctest+Lost+connection+to+testmanagerd&gs_lcp=CgZwc3ktYWIQAzIFCCEQoAEyBQghEKABUIIFWIIFYNYIaABwAHgAgAFtiAFtkgEDMC4xmAEAoAECoAEBqgEHZ3dzLXdpeg&sclient=psy-ab&ved=0ahUKEwiC59iwoLnuAhXvFjQIHQDLAWMQ4dUDCAk&uact=5

**Comment by gffguo** [comment]
@KazuCocoa Thank you very much. This gives me a direction and train of thought to check my problems，
