### ISSUE TITLE
What is the minimum version of iOS system supported by MJPEG-Server

### ISSUE THREAD

**Issue by jianghuihon** [appium/WebDriverAgent#912]
If I want to use MJPEG-Server, what is the minimum version of iOS system supported? It seems to be 12.0.1. If there are iOS9 and iOS10, please tell me in which branch or which submitted node, thank you

**Comment by KazuCocoa** [comment]
What version of WDA did you use? 
As https://appium.github.io/appium-xcuitest-driver/latest/installation/requirements/ , this WDA could have issues for lower than iOS 15 after XCUITest driver 4.27.2.
https://github.com/appium/WebDriverAgent/blob/master/CHANGELOG.md#500-2023-05-14 is the WDA version which dropped lower versions.

**Comment by jianghuihon** [comment]
I use the latest master branch, set the lowest version to 9.1, the result is that there is no picture data on the MJPEG-Server 9100 port, I would like to ask how to support the system of ios 9.1, and the MJPEG-Server 9100 port has picture data?

**Comment by KazuCocoa** [comment]
Since some WDA code might not be compatible with such lower OS versions. We no longer support such OS version as Appium/WDA as https://appium.github.io/appium-xcuitest-driver/latest/installation/requirements/.

Perhaps you could bring https://github.com/appium/WebDriverAgent/pull/721 back into your forked repository to support old versions again for your case. Or perhaps you could fork WDA code from WDA v4.15.1 if you need it.
