### ISSUE TITLE
Getting WebDriverAgent version from IPA/Zip file

### ISSUE THREAD

**Issue by mega6453** [appium/WebDriverAgent#958]
Hi,
I want to know the WebDriverAgent version by parsing the info.plist file. But what I can see is the version is 1.0 always as below.

	<key>CFBundleShortVersionString</key>
	<string>1.0</string>

And I couldn't find the right version from the info.plist from any other key. Is there any way I can get the version from the file?

**Comment by KazuCocoa** [comment]
It's because of XCTest package. The top level's `Into.plist` is always 1.0 by xcodebuild while we modify the version info before the xcodebuild build. You need to read `Info.plist` in `PlugIns/WebDriverAgentRunner.xctest/Frameworks/WebDriverAgentLib.framework/Info.plist` which hasn't been replaced by xcodebuild

**Comment by mega6453** [comment]
@KazuCocoa Thanks, that worked.
